
work_dir: ./work_dir/chalearn_500/logsig_gcn_1000_c288_seg16

# feeder
feeder: feeders.feeder_chalearn.Feeder
train_feeder_args:
  data_path: ./data/chalearn/train_data.npy
  label_path: ./data/chalearn/train_label.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/chalearn/val_data.npy
  label_path: ./data/chalearn/val_label.npy

# model
model: model.logsig_gcn_chalearn.Model
model_args:
  num_class: 20
  num_point: 19
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.chalearn.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.01
step: [30, 60]

# training
num_epoch: 200
device: [0]
batch_size: 32
forward_batch_size: 16
test_batch_size: 32
nesterov: True
