# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  length_path: ./data/ntu120/xsub/val_data_len.npy
  debug: False
  use_mmap: False
  robust_add: False
  robust_drop: False
  ucl_implementation: False ## NOTE THIS!
  frame_method: 'delete' # acceptable params: 'delete', 'repeat_previous', 'repeat_next', 'interpolate', 'expected_ucl'
  add_rate: 0.00
  drop_rate: 0.1
  structured_degradation: False
  structured_degradation_type: 'frame_rate' # acceptable params: 'reduced_resolution', 'frame_rate'
  structured_res: 6
  FPS: 3
  chunks: 1
  mitigation: True
  spatial_deg: True

# model
model: model.gcn_logsigRNN.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  #num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# test
phase: test
device: [0]
test_batch_size: 32
weights: ./work_dir/ntu120/xsub/gcn_logsigrnn/weights/weights-27-106353.pt

work_dir: ./eval/ntu120_var/drop/delete_0.5/logsig
save_score: True


# python3 main.py --config=config/ntu_sub/test_joint.yaml --device 0
