# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  length_path: ./data/ntu120/xsub/val_data_len.npy
  debug: False
  use_mmap: False
  robust_add: True
  robust_drop: False
  add_rate: 0.5
  drop_rate: 0.0
  

# model
model: model.logsig_gcn_var.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# test
phase: test
device: [0]
test_batch_size: 32
weights: ./work_dir/ntu120/xsub_var/logsig_gcn_v2_c96_192_lr_0.02/weights/weights-26-102414.pt

work_dir: ./eval/ntu120_var/test/logsig
save_score: True
