
work_dir: ./work_dir/ntu120/xsub_var/logsig_gcn_v2_c96_192_lr_0.02

# feeder
feeder: feeders.feeder_var.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xsub/train_data_joint.npy
  label_path: ./data/ntu120/xsub/train_label.pkl
  length_path: ./data/ntu120/xsub/train_data_len.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  length_path: ./data/ntu120/xsub/val_data_len.npy

# model
model: model.gcn_logsig_var.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.02
step: [10, 20]

# training
num_epoch: 60
device: [0]
batch_size: 16
forward_batch_size: 16
test_batch_size: 16
nesterov: True
